### ISSUE TITLE
0.107.0 Issue

### ISSUE THREAD

**Issue by apedance** [wxt9861/esxi_stats#24]
Hello,

seems like the latest update is messing with esxi_stats:

Log Details (ERROR)
Logger: homeassistant.config_entries
Source: custom_components/esxi_stats/__init__.py:102
First occurred: 11:52:35 PM (1 occurrences)
Last logged: 11:52:35 PM

Error setting up entry 192.168.1.76 for esxi_stats
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 216, in async_setup
    hass, self
  File "/config/custom_components/esxi_stats/__init__.py", line 102, in async_setup_entry
    config[DOMAIN]["monitored_conditions"] = []
TypeError: 'mappingproxy' object does not support item assignment

**Comment by apedance** [comment]
Fixes on the way. Can't read.
