### ISSUE TITLE
KeyError: 'notify'

### ISSUE THREAD

**Issue by megapearl** [wxt9861/esxi_stats#69]
**Describe the bug**
Upon startup of home assistant an error is generated in the logs.

**To Reproduce**
Install latest beta version of esxi_stats and reboot homeassistant.

**Expected behavior**
No errors

**Screenshots**

**ESXi environment (please complete the following information):**
vCenter as vm on ESXi 6.7

**Additional context**

Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/config_entries.py", line 335, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/home/homeassistant/.homeassistant/custom_components/esxi_stats/__init__.py", line 139, in async_setup_entry
    async_add_services(hass, config_entry)
  File "/home/homeassistant/.homeassistant/custom_components/esxi_stats/__init__.py", line 298, in async_add_services
    notify = config_entry.options["notify"]
KeyError: 'notify'

**Comment by wxt9861** [comment]
This is addressed in 0.7.0.beta7
