### ISSUE TITLE
failed to setup

### ISSUE THREAD

**Issue by walkerjohnsonofficial** [wxt9861/esxi_stats#84]
Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/hacs/repositories/base.py:995
Integration: websocket_api (documentation, issues)
First occurred: 00:40:48 (1 occurrences)
Last logged: 00:40:48

[140296593491920] Error handling message: Unknown error (unknown_error) 109443322 from 192.168.0.107 (Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/115.0)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 26, in _handle_async_response
    await func(hass, connection, msg)
  File "/config/custom_components/hacs/websocket/repository.py", line 216, in hacs_repository_download
    await repository.async_install()
  File "/config/custom_components/hacs/repositories/base.py", line 899, in async_install
    await self.async_install_repository()
  File "/config/custom_components/hacs/repositories/base.py", line 995, in async_install_repository
    raise HacsException("Could not download, see log for details")
custom_components.hacs.exceptions.HacsException: Could not download, see log for details
Sorry to trouble you, 
I encountered this problem after I created the entity. Is there something wrong or I missed it? grateful!

**Comment by wxt9861** [comment]
This is an error you get when you added repo to custom repositories in HACS?

**Comment by walkerjohnsonofficial** [comment]
[home-assistant_esxi_stats_2023-07-12T18-31-32.831Z.log](https://github.com/wxt9861/esxi_stats/files/12031342/home-assistant_esxi_stats_2023-07-12T18-31-32.831Z.log)

**Comment by wxt9861** [comment]
How did you install the component? It is failing at startup because there are missing files.

2023-07-13 02:42:42.352 CRITICAL (SyncWorker_3) [custom_components.esxi_stats] The following files are missing: ['sensor.py']

**Comment by walkerjohnsonofficial** [comment]
it's working, thanks!!
