### ISSUE TITLE
Component does not start with HA 2024.2.1

### ISSUE THREAD

**Issue by Kedryn** [wxt9861/esxi_stats#99]
**Describe the bug**
with HA 2024.2.0 the component does not start

**To Reproduce**
update HA to 2024.2.0

**Expected behavior**
To start as before

`Logger: homeassistant.setup
Source: setup.py:251
First occurred: 09:32:39 (1 occurrences)
Last logged: 09:32:39

Setup failed for custom integration 'esxi_stats': Unable to import component: Exception importing custom_components.esxi_stats
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 827, in get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 994, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/esxi_stats/__init__.py", line 7, in <module>
    from .esxi import (
  File "/config/custom_components/esxi_stats/esxi.py", line 4, in <module>
    from pyVim.connect import SmartConnect, SmartConnectNoSSL
  File "/usr/local/lib/python3.12/site-packages/pyVim/connect.py", line 37, in <module>
    from pyVmomi import vim, vmodl, SoapStubAdapter, SessionOrientedStub
  File "/usr/local/lib/python3.12/site-packages/pyVmomi/__init__.py", line 39, in <module>
    from pyVmomi.SoapAdapter import SoapStubAdapter, StubAdapterBase, SoapCmdStubAdapter, \
  File "/usr/local/lib/python3.12/site-packages/pyVmomi/SoapAdapter.py", line 1003, in <module>
    _SocketWrapper = ssl.wrap_socket
                     ^^^^^^^^^^^^^^^
AttributeError: module 'ssl' has no attribute 'wrap_socket'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 251, in _async_setup_component
    component = integration.get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 835, in get_component
    raise ImportError(f"Exception importing {self.pkg_path}") from err
ImportError: Exception importing custom_components.esxi_stats`

`Logger: homeassistant.loader
Source: loader.py:827
First occurred: 09:32:39 (1 occurrences)
Last logged: 09:32:39

Unexpected exception importing component custom_components.esxi_stats
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 827, in get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 994, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/esxi_stats/__init__.py", line 7, in <module>
    from .esxi import (
  File "/config/custom_components/esxi_stats/esxi.py", line 4, in <module>
    from pyVim.connect import SmartConnect, SmartConnectNoSSL
  File "/usr/local/lib/python3.12/site-packages/pyVim/connect.py", line 37, in <module>
    from pyVmomi import vim, vmodl, SoapStubAdapter, SessionOrientedStub
  File "/usr/local/lib/python3.12/site-packages/pyVmomi/__init__.py", line 39, in <module>
    from pyVmomi.SoapAdapter import SoapStubAdapter, StubAdapterBase, SoapCmdStubAdapter, \
  File "/usr/local/lib/python3.12/site-packages/pyVmomi/SoapAdapter.py", line 1003, in <module>
    _SocketWrapper = ssl.wrap_socket
                     ^^^^^^^^^^^^^^^
AttributeError: module 'ssl' has no attribute 'wrap_socket'`

**Comment by ansred** [comment]
Correct it’s broken with HA 2024.2.1

Couple screenshots here

![IMG_4211](https://github.com/wxt9861/esxi_stats/assets/5244872/b858f3bb-86d6-46b1-9538-f17642d2f3e4)
![IMG_4212](https://github.com/wxt9861/esxi_stats/assets/5244872/095e2514-5d78-4b63-9825-6c4849b75620)

**Comment by wxt9861** [comment]
What version of the component are you using? Your logs suggest you might be using version 0.6x which depends on an older version of pyvmomi which might(?) have compatibility issues with python 3.12.

Also, does the error persist through HASS restarts?

**Comment by ansred** [comment]
Update:
@wxt9861 I was running outdated version of the HACS, once updated and restarted,
![Screenshot 2024-02-12 at 2 20 51 PM](https://github.com/wxt9861/esxi_stats/assets/5244872/397eabba-c626-46e1-979d-d9f462f0868c)
 that fixed the issue

**Comment by Kedryn** [comment]
> Update: @wxt9861 I was running outdated version of the HACS, once updated and restarted, ![Screenshot 2024-02-12 at 2 20 51 PM](https://private-user-images.githubusercontent.com/5244872/304200619-397eabba-c626-46e1-979d-d9f462f0868c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc3NzM4NDksIm5iZiI6MTcwNzc3MzU0OSwicGF0aCI6Ii81MjQ0ODcyLzMwNDIwMDYxOS0zOTdlYWJiYS1jNjI2LTQ2ZTEtOTc5ZC1kOWY0NjJmMDg2OGMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMTJUMjEzMjI5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTNhMjM0YzgyYjllYzhkMjMzYmJlOTE2NTVjODY4NTcwYWI5YzE1MDViYzA4NzIzZDNiNThiMzAzYjliNGM1OCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.cTYGQvL0sJAlVwV5HUu9QwDOWfkNRtCwl6UJRFCxdq4) that fixed the issue

that fixed for me too, thanks!

**Comment by Gatlarf** [comment]
The update fixed it for me too. I did a manual install when I set this up initally. I now added the repo and installed from there, without removing the manual installation first. Very happy to have my stats back and thank you for your excellent work. 

Off-topic: Now, let’s hope Broadcom will revert their decision on ESXI…

**Comment by wxt9861** [comment]
@Gatlarf will stay hopeful. I have no plans to migrate to another hypervisor at this time so this component should stay active, as time permits.
